cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('get_available_dates/', views.get_available_dates, name='get_available_dates'),
    path('get_available_time_slots/', views.get_available_time_slots, name='get_available_time_slots'),
    path('billing/', views.billing, name='billing'),
    path('remove_cart_item/', views.remove_cart_item, name='remove_cart_item'),
]

razorpayAPI/urls.py
from django.urls import path
from . import views

app_name = "razorpay"

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('failure/', views.paymentfailure, name='paymentfailure'),
]

venkatesh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clickfix.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('razorpay/', include('razorpayAPI.urls')),
    path('discount/', include('discount.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/razorpay/failure.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Payment Failure {% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}

    <h1 class="text-center my-5">Payment Failure Page</h1>
    {% include 'includes/footer.html' %}

{% endblock %}

templates/razorpay/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Payment {% endblock %}

{% block content %}

    {% block extra_js %}
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
        <script>
            var options = {
                key: "{{ razorpay_merchant_key }}",
                amount: "{{ razorpay_amount }}",
                currency: "{{ currency }}",
                name: "ClickFix",
                order_id: "{{ razorpay_order_id }}",
                callback_url: "{{ callback_url }}",
            };
            console.log(options)
            var rzp = new Razorpay(options);
            rzp.open();
        </script>
    {% endblock %}
{% endblock %}

templates/razorpay/start_payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Start Payment {% endblock %}

{% block content %}

    <form action="{% url 'razorpay:payment' %}" method="post" id="myform">
        <input type="hidden" name="amount" id="amount" value="{{ total_amount }}">
        {% for order_obj in order_objects_list %}
            <input type="hidden" name="order_id_{{ forloop.counter }}" id="order_id_{{ forloop.counter }}" value="{{ order_obj.id }}">
        {% endfor %}
    </form>

<!--
    <form action="{% url 'razorpay:payment' %}" method="post" id="myform">
        <input type="hidden" name="amount" id="amount" value="{{ amount }}">
        <input type="hidden" name="order_id" id="order_id" value="{{ order_id }}">
    </form> -->

{% block extra_js %}
    <script>
        window.addEventListener('load', function() {
            var form = document.getElementById('myform');
            form.submit();
        });
    </script>
    {% endblock %}
{% endblock %}