accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('get_available_dates/', views.get_available_dates, name='get_available_dates'),
    path('get_available_time_slots/', views.get_available_time_slots, name='get_available_time_slots'),
    path('billing/', views.billing, name='billing'),
    path('remove_cart_item/', views.remove_cart_item, name='remove_cart_item'),
]

clickfix/urls.py
from django.urls import path
from . import views

app_name = "clickfix"

urlpatterns = [
    path('', views.home, name='home'),
    path('service/<slug:service_name>/', views.individual_service, name='individual_service'),
    path('checkout/', views.checkout, name='checkout'),
    path('live_tracking/', views.live_tracking, name='live_tracking'),
    path('bookings/', views.bookings, name='bookings'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search_view, name='search'),
    path('book_rent_call/', views.book_rent_call, name='book_rent_call'),
    path('book_amc_call/', views.book_amc_call, name='book_amc_call'),
]

venkatesh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clickfix.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('razorpay/', include('razorpayAPI.urls')),
    path('discount/', include('discount.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}

<footer class="shadow-lg">
    <div class="container px-3">
        <div class="d-flex justify-content-between pt-5 flex-wrap">
            <img class="img-fluid footer_logo_image" src="{% static 'img/logo.png' %}" style="width: 150px;" alt="">
            <div class="d-flex align-items-center">
                <a href="https://www.facebook.com/profile.php?id=61551230633366&mibextid=avESrC" target="_blank"><img class="img-fluid me-2" style="height: 80%;" src="{% static 'img/facebook.png' %}" alt=""></a>
                <a href="#"><img class="img-fluid me-2" style="height: 80%;" src="{% static 'img/twitter.png' %}" alt=""></a>
                <a href="#"><img class="img-fluid me-2" style="height: 80%;" src="{% static 'img/linkedin.png' %}" alt=""></a>
                <a href="https://www.instagram.com/_clickfix_?utm_source=qr" target="_blank"><img class="img-fluid me-2" style="height: 80%;" src="{% static 'img/instagram.png' %}" alt=""></a>
            </div>
        </div>
        <div class="my-5" style="border: 1px solid #f6921e;"></div>
        <div class="row mb-5">
            <div class="col-md-2 col-sm-6 col-6 mb-4">
                <h4 class="mb-4">Explore</h4>
                <ul class="list-unstyled">
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="{% url 'clickfix:home' %}">Home</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="{% url 'clickfix:home' %}#about">About Us</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="{% url 'clickfix:home' %}#services">Services</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="{% url 'clickfix:home' %}#contact_form">Contact Us</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="{% url 'clickfix:home' %}#contact_form">Register as professional</a></li>
                </ul>
            </div>
            <div class="col-md-2 col-6 mb-5">
                <h4 class="mb-4">Services</h4>
                <ul class="list-unstyled">
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">Laptop</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">Phone</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">Desktop</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">Tablet</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">CCTV</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#">Server</a></li>
                    <li class="mb-2"><a class="text-decoration-none text-dark" href="#"></a></li>
                </ul>
            </div>
            <div class="col-md-5 col-sm-6 mb-5">
                <h4 class="mb-4">Keep in Touch</h4>
                <div class="row mb-3">
                    <div class="col-3">Address: </div>
                    <div class="col-9">E Mall  - Shop No, 116/117 6, Chittaranjan Ave, Kolkata, West Bengal, 700072</div>
                </div>

                <div class="row mb-3">
                    <div class="col-3">Mail: </div>
                    <div class="col-9">support@clickfix.co.in</div>
                </div>

                <div class="row mb-3">
                    <div class="col-3">Contact: </div>
                    <div class="col-9">+91 89104 34505 / +91 98360 66464</div>
                    <div class="col-9"></div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <h4 class="mb-4">Working Hours</h4>
                <div class="row mb-3">
                    <div class="col-4">Mon to Fri: </div>
                    <div class="col-8">10am - 6am</div>
                </div>
                <div class="row mb-3">
                    <div class="col-4">Sat: </div>
                    <div class="col-8">10am - 4pm</div>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center align-items-center py-4" style="background-color: black; color: white;">
        <p class="mb-0">&copy; 2023 clickfix. All rights reserved.</p>
    </div>
</footer>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div id="id" class="container">
            <div class="alert alert-{{message.tags}} fade show" alert-dismissable role="alert">
                <div class="d-flex justify-content-between">
                    <div>
                        {{ message }}
                    </div>
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="True">&times;</span>
                    </button>
                </div>

            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div class="container">
          <a class="navbar-brand" href="{% url 'clickfix:home' %}"><img src="{% static 'img/logo.png' %}" alt="" style="width: 150px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link text-dark fw-bold me-4" aria-current="page" href="{% url 'clickfix:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark fw-bold me-4" href="{% url 'clickfix:home' %}#services">Services</a></li>
                <li class="nav-item"><a class="nav-link text-dark fw-bold me-4" href="{% url 'clickfix:home' %}#about">About</a></li>
                <li class="nav-item"><a class="nav-link text-dark fw-bold me-4" href="{% url 'clickfix:home' %}#contact_form">Contact</a></li>
                <li class="nav-item">
                  <a class="nav-link text-dark fw-bold me-4" href="{% url 'cart:cart' %}">
                    <i class="fa-solid fa-cart-shopping"></i> <span class="num_of_items">{{cart.num_of_items}}</span>
                    <span class="d-inline-block d-md-none ms-1">Cart</span>
                  </a>
                </li>


                <li class="nav-item dropdown me-4 pull-right">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user text-dark"></i>
                    <span class="d-inline-block d-md-none text-dark ms-1 fw-bold">User</span>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'clickfix:bookings' %}">My bookings</a></li>
                  </ul>
                </li>
            </ul>
          </div>
        </div>
      </nav>