accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('get_available_dates/', views.get_available_dates, name='get_available_dates'),
    path('get_available_time_slots/', views.get_available_time_slots, name='get_available_time_slots'),
    path('billing/', views.billing, name='billing'),
    path('remove_cart_item/', views.remove_cart_item, name='remove_cart_item'),
]

clickfix/urls.py
from django.urls import path
from . import views

app_name = "clickfix"

urlpatterns = [
    path('', views.home, name='home'),
    path('service/<slug:service_name>/', views.individual_service, name='individual_service'),
    path('checkout/', views.checkout, name='checkout'),
    path('live_tracking/', views.live_tracking, name='live_tracking'),
    path('bookings/', views.bookings, name='bookings'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search_view, name='search'),
    path('book_rent_call/', views.book_rent_call, name='book_rent_call'),
    path('book_amc_call/', views.book_amc_call, name='book_amc_call'),
]

discount/urls.py
from django.urls import path
from . import views

app_name = "discount"

urlpatterns = [
    path('remove_coupon/<cart_id>/', views.remove_coupon, name="remove_coupon"),
]

venkatesh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clickfix.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('razorpay/', include('razorpayAPI.urls')),
    path('discount/', include('discount.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from clickfix.models import *
from accounts.models import *
from discount.models import *


class Cart(models.Model):
    class Meta:
        verbose_name_plural = 'Cart'

    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    session_id = models.CharField(max_length=100, null=True, blank=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_cart_total(self):
        cart_items = self.cartitems.all()
        price = []
        for cart_item in cart_items:
            price.append(cart_item.sub_service.sub_service_price)

        if self.coupon:
            if self.coupon.minimum_price < sum(price):
                return sum(price) - self.coupon.discount_price
        return sum(price)

    def __str__(self):
        if self.user:
            return self.user.username
        else:
            return "Guest"

    @property
    def num_of_items(self):
        cartitems = self.cartitems.all()
        quantity =  sum([item.quantity for item in cartitems])
        return quantity


class CartItem(models.Model):
    class Meta:
        verbose_name_plural = 'Cart Items'

    TIME_SLOTS = (
        ("10am-12pm", "10am-12pm"),
        ("12pm-2pm", "12pm-2pm"),
        ("2pm-4pm", "2pm-4pm"),
        ("4pm-7pm", "4pm-7pm"),
    )
    sub_service = models.ForeignKey(SubServices, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cartitems")
    quantity = models.IntegerField(default=0)
    start_date = models.DateField(null=True)
    time_slot = models.CharField(max_length=20, choices=TIME_SLOTS, default=1)

    def __str__(self):
        return self.sub_service.sub_service_name

    @property
    def price(self):
        new_price = self.sub_service.sub_service_price * self.quantity
        return new_price



class BillingDetails(models.Model):
    class Meta:
        verbose_name_plural = 'Billing Details'

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=150)
    phone = models.CharField(max_length=15)
    address_line_1 = models.TextField()
    address_line_2 = models.TextField(blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.id} - {self.first_name} {self.last_name}"

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
from clickfix.models import SubServices
from .models import *
import uuid
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from django.db.models import Count
from razorpayAPI.models import Order, OrderItem
from discount.models import Coupon
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail


def getDate(date):
    current_date = datetime.now().date()
    start_date = datetime.strptime(date, '%Y-%m-%d').date()

    if start_date < current_date:
        start_date += relativedelta(months=1)

    date_range_start = current_date
    date_range_end = current_date + timedelta(days=6)

    if start_date >= date_range_start and start_date <= date_range_end:
        start_date = start_date.strftime("%Y-%m-%d")
        return start_date
    return None


def get_cart(request):
    try:
        if request.user.is_authenticated:
            cart = Cart.objects.get(user=request.user)
        else:
            cart = Cart.objects.get(session_id=request.session['nonuser'])
    except:
        cart = None
    return cart


# NOTE: we have to send cart object to all functions so that it could be rendered on top right cart icon
def cart(request):
    cart = get_cart(request)
    cart_items = None
    if cart:
        cart_items = cart.cartitems.all()

    if request.method == "POST":
        coupon_code = request.POST.get('coupon')
        coupon_obj = Coupon.objects.filter(coupon_code__iexact=coupon_code)[0]

        if cart.coupon:
            messages.warning(request, "Coupon Already Exists.")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        if cart.get_cart_total() < coupon_obj.minimum_price:
            messages.warning(request, f"Amount Should be greater than {coupon_obj.minimum_price}.")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        if coupon_obj.is_expired:
            messages.danger(request, "Coupon Expired")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        cart.coupon = coupon_obj
        cart.save()
        messages.success(request, "Coupon Applied!")

    data = {}
    data['cart'] = cart
    data['cart_items'] = cart_items
    data['coupons'] = Coupon.objects.filter(is_expired=False)
    if cart:
        data['cart_total'] = cart.get_cart_total()

    return render(request, 'cart.html', data)


def add_to_cart(request):
    data = json.loads(request.body)
    sub_service = SubServices.objects.get(id=data['sub_service_id'])
    day = data['date_slot']
    date_slot = getDate(day)
    time_slot = id=data['time_slot']

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user)
    else:
        if "nonuser" in request.session:
            session_id = request.session['nonuser']
        else:
            session_id = str(uuid.uuid4())
            request.session['nonuser'] = session_id
        cart, created = Cart.objects.get_or_create(session_id=session_id)

    cart_item, created = CartItem.objects.get_or_create(cart=cart, start_date=date_slot, time_slot=time_slot, sub_service=sub_service)
    cart_item.quantity += 1
    cart_item.save()
    num_of_items = cart.num_of_items

    return JsonResponse(num_of_items, safe=False)


def get_available_dates(request):
    date_disable_map = {}
    data = json.loads(request.body)
    today = datetime.now().date()
    available_dates = [(today + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(7)]
    for date in available_dates:
        date_disable_map[date] = False


    booked_date_slots = OrderItem.objects.filter(sub_service=data['sub_service_id']).values('start_date').annotate(total_time_slots=Count('time_slot'))
    for slot in booked_date_slots:
        temp_date = slot['start_date'].strftime('%Y-%m-%d')
        total_slots = slot['total_time_slots']
        if total_slots == 4:
            date_disable_map[temp_date] = True

    return JsonResponse(date_disable_map, safe=False)


def get_available_time_slots(request):
    time_disable_map = {}
    data = json.loads(request.body)
    booked_time_slots = OrderItem.objects.filter(sub_service=data['sub_service_id'], start_date=data['date_slot'])

    time_slots = ["10am-12pm", "12pm-2pm", "2pm-4pm", "4pm-7pm"]
    for slot in time_slots:
        time_disable_map['slot'] = False

    for slot in booked_time_slots:
        time_disable_map[slot.time_slot] = True

    return JsonResponse(time_disable_map, safe=False)


def send_customer_mail(customer_email, customer_name, service_type):
    if len(service_type) == 1:
        service_type = service_type[0]
    else:
        service_type = "\n" + "\n".join([f"{i + 1}. {service}" for i, service in enumerate(service_type)])

    subject = "Booking Confirmation - Thank You for Choosing ClickFix!"
    body = f"Dear {customer_name},\nThank you for choosing ClickFix! Your booking is confirmed\nService Type: {service_type} \n\nIf you have any questions or need assistance, please reach out to our customer support team at support@clickfix.co.in or +91 8910434505. \n\nWarm regards, \nClickFix Customer Services"

    send_mail(
        subject=subject,
        message=body,
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[customer_email],
        fail_silently=True,
    )


@login_required()
def billing(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        address_line_1 = request.POST.get('address_line_1')
        address_line_2 = request.POST.get('address_line_2')
        city = request.POST.get('city')
        state = request.POST.get('state')
        payment_method = request.POST.get('payment_method')

        billing_obj = BillingDetails.objects.create( first_name = first_name , last_name = last_name , email = email , phone = phone , address_line_1 = address_line_1 , address_line_2 = address_line_2 , city = city , state = state)

# ***************************************************************************************************************************************************************************************************
        current_user = None
        cart = None
        if request.user.is_authenticated:
            user = request.user
            cart = Cart.objects.get(user=user)
            current_user = user
        else:
            session_id = request.session['nonuser']
            cart = Cart.objects.get(session_id=session_id)
            current_user = session_id

        order_objects_list = []
        booked_services_names = []
        total_order_amount = cart.get_cart_total()
        for item in cart.cartitems.all():
            service_name = item.sub_service.sub_service_name
            booked_services_names.append(service_name)

            order_obj = Order(billing_details=billing_obj)
            if request.user.is_authenticated:
                order_obj.user = current_user
            else:
                order_obj.session_id = current_user
            order_obj.cart_id = cart.id
            order_obj.total_cost = cart.get_cart_total()
            order_obj.save()

            order_item_obj = OrderItem()
            order_item_obj.order = order_obj
            order_item_obj.sub_service = item.sub_service
            order_item_obj.quantity = item.quantity
            order_item_obj.start_date = item.start_date
            order_item_obj.time_slot = item.time_slot
            order_item_obj.save()

            if payment_method == "cash_on_delivery":
                order_obj.payment_mode = "cash_on_delivery"
                order_obj.save()
            order_objects_list.append(order_obj)


        if payment_method == "cash_on_delivery":
            Cart.objects.get(id=cart.id).delete()       # deleting our cart cause our order placed successfully
            send_customer_mail(email, first_name, booked_services_names)
            messages.success(request, "Order Placed Successfully")
            return redirect('clickfix:bookings')

        send_customer_mail(email, first_name, booked_services_names)
        return render(request, 'razorpay/start_payment.html', {'total_amount': total_order_amount, 'order_objects_list': order_objects_list})

# ***************************************************************************************************************************************************************************************************


        # order_obj = Order(billing_details=billing_obj)
        # if request.user.is_authenticated:
        #     user = request.user
        #     cart = Cart.objects.get(user=user)
        #     order_obj.user = user
        # else:
        #     session_id = request.session['nonuser']
        #     cart = Cart.objects.get(session_id=session_id)
        #     order_obj.session_id = session_id

        # order_obj.cart_id = cart.id
        # order_obj.total_cost = cart.get_cart_total()
        # order_obj.save()

        # # Shifting our Cart Items to Order Items
        # for item in cart.cartitems.all():
        #     order_item_obj = OrderItem()
        #     order_item_obj.order = order_obj
        #     order_item_obj.sub_service = item.sub_service
        #     order_item_obj.quantity = item.quantity
        #     order_item_obj.start_date = item.start_date
        #     order_item_obj.time_slot = item.time_slot
        #     order_item_obj.save()

        # if payment_method == "cash_on_delivery":
        #     order_obj.payment_mode = "cash_on_delivery"
        #     # Since Order Placed Successfully So remove all items from our cart

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">

    <!-- Bootstrap stylesheet-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Swiper stylesheet -->
    <link rel="stylesheet" href="{% static 'css/slider/swiper.bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider/swiper_custom.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">


    <style>
        @font-face {
            font-family: 'metropolis';
            src: url("./assets/fonts/Metropolis-Black.otf") format("opentype");
            font-style: normal;
        }


        @font-face {
            font-family: 'bahnschrift';
            src: url("./assets/fonts/BAHNSCHRIFT.ttf") format("opentype");
            font-style: normal;
        }

        body{
            box-sizing: border-box;
            font-family: 'bahnschrift';
        }

        .headings{
            font-family: 'metropolis';
        }

        h1, h2, h3, h4, h5, h6, p, a{
            font-family: 'bahnschrift';
        }
    </style>

    {% block extra_css %}
    {% endblock %}

</head>

<body>

    {% block content %}
    {% endblock %}




    <!-- Custom JavaScript -->
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- Bootstrap JavaScript -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Swiper JavaScript -->
    <script src="{% static 'js/slider/swiper.bundle.min.js' %}"></script>
    <script src="{% static 'js/slider/slider_custom.js' %}"></script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js"></script>

    <!-- Typed Text JS -->
    <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>

    {% block extra_js %}
    {% endblock %}

</body>

</html>

templates/bookings.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Bookings {% endblock %}

{% block extra_css %}
    <style>
        .btn-outline-warning {
            border-color: #F6921E;
            color: #F6921E;
        }
        .btn-outline-warning:hover {
            border-color: #F6921E;
        }
    </style>
{% endblock %}
{% block content %}

    {% include 'includes/navbar.html' %}
    <div style="position: absolute;  top: 100px; right: 0;">
        {% include 'includes/messages.html' %}
    </div>

    <div class="container my-5">
        {% if order_items %}
        <h1 class="mb-5">My Bookings</h1>
        {% endif %}
        <div class="row">
            {% for item in order_items %}
            <div class="col-md-6 mb-3">
                <div class="d-flex flex-column rounded p-4" style="border: 1px solid #BADBFF;">
                    <div class="d-flex flex-column">
                        {% if item.order.booking_status == "Upcoming" %}
                            <p class="text-uppercase" style="color: #25d366;">UPCOMING</p>
                        {% elif item.order.booking_status == "Booking Not Accepted" or item.order.payment_status == "Failed" %}
                            <p class="text-uppercase text-danger">BOOKING NOT ACCEPTED</p>
                        {% elif item.order.booking_status == "Rescheduled" %}
                            <p class="text-uppercase text-warning">Rescheduled</p>
                        {% elif item.order.booking_status == "Job Completed" %}
                            <p class="text-uppercase" style="color: #25d366;">Job Completed</p>
                        {% endif %}


                        <h2>{{ item.sub_service }}</h2>
                        <p class="mb-0"></p>
                        <p class="mb-0"></p>
                    </div>
                    <div class="my-4" style="border:1px solid #BADBFF;"></div>
                    <div class="row">
                        <div class="col-md-6 col-12 mb-3">
                            {% if item.order.payment_status == "Failed" %}
                                <span>Payment Failed</span>
                            {% else %}
                                {% if item.order.payment_mode == "cash_on_delivery" and not item.order.show_amount_in_bookings %}
                                <span>Cash on Delivery</span>
                                {% else %}
                                <span>Total Amount Paid ₹{{item.order.total_cost}}</span>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="col-12">
                            <div class="d-flex">
                                <!-- <button class="me-2 btn btn-outline-warning">Reschedule</button> -->

                                {% if item.order.payment_status == "Failed" %}
                                    <a href="{% url 'cart:cart' %}" class="me-2 btn btn-outline-warning">Retry</a>
                                {% else %}
                                    <!-- <button class="me-2 btn btn-outline-danger">Cancel</button> -->
                                    <form action="{% url 'clickfix:live_tracking' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="order_item_id" value="{{ item.id }}">
                                        <button href="{% url 'clickfix:live_tracking' %}" type="submit" class="btn btn-outline-dark">Track</button>
                                    </form>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <h1 class="text-muted text-center">No Bookings</h1>
            {% endfor %}
        </div>
    </div>


    {% include 'includes/footer.html' %}
{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cart {% endblock %}


{% block content %}

    {% include 'includes/navbar.html' %}

    <div class="container mt-5" id="cart">
        <h1 class="mb-5">Cart</h1>
        <div class="row">
            <!-- User Details and payment summary -->
            <div class="col-md-6 col-sm-12  p-3">
                <div class="d-flex justify-content-between align-items-center">

                    {% if cart_items %}
                    <span class="blockquote fw-bold mb-4" id="service_booked_heading">Services Booked</span>
                    <span id="checkout_form">
                        <form action="{% url 'clickfix:checkout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn_color fw-bold mb-4 d-flex align-items-center" id="checkout_button">Proceed to checkout <i class="fa-solid fa-caret-right ms-2"></i></button>
                        </form>
                    </span>
                    {% endif %}
                </div>
                {% for item in cart_items %}
                <div class="row my-4" id="cart_item_{{item.id}}">
                    <div class="col-4">
                        <img class="img-fluid cart_img mr-3" src="{{ item.sub_service.sub_service_main_image.url }}" alt="">
                    </div>
                    <div class="col-8">
                        <div class="d-flex flex-column justify-content-center h-100">
                            <div class="">
                                <div class="d-flex justify-content-between w-100">
                                    <h5>{{ item.sub_service.sub_service_name }} </h5>
                                    <div>Rs {{ item.sub_service.sub_service_price }}/-</div>
                                </div>
                                <div>Service Date: {{ item.start_date }}</div>
                                <div>Time Slot: {{ item.time_slot }}</div>
                                <div class="d-flex justify-content-between">
                                    <span>Quantity: {{ item.quantity }}</span>
                                    <span onclick="handleCartItemRemoval('{{ item.id }}', '{{ item.cart.id }}')" style="cursor: pointer;"><i class="fa-solid fa-trash text-danger"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if not forloop.last %}
                    <div class="my-3" style="border: 1px solid #f6911e25;"></div>
                    {% endif %}
                </div>

                {% empty %}
                <h3 class="text-muted" id="empty_cart_text">Nothing in Cart!</h3>
                {% endfor %}
            </div>

            {% if cart.cartitems %}
            <!-- For Cart and coupon applied -->
            <div class="col-md-6 col-sm-12 p-3 coupon_section">
                <div>
                    <!-- APPLY COUPON -->
                    {% include 'includes/messages.html' %}
                    <div class="d-flex justify-content-between align-items-center p-4" style="border: 1px solid #f6911e75; border-radius: 10px;">
                        <div class="d-flex">
                            <div class="d-flex justify-content-center align-items-center text-white coupon_img">
                                <span>%</span>
                            </div>
                            <div class="d-flex flex-column justify-content-center ms-4">
                                <div class="">Coupons and Offers</div>
                            </div>
                        </div>
                        <a href="" class="text-danger text-decoration-none" data-bs-toggle="modal" data-bs-target="#couponModal">{{coupons|length}} Offers > </a>
                    </div>
                    <!-- COUPON MODAL -->
                    <div class="modal fade" id="couponModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="myModalLabel">
                                        Coupons & Offers
                                    </h1>
                                    <button class="btn-close" data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body  px-4">
                                    {% for coupon in coupons %}
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="d-flex">
                                            {% if coupon.image %}
                                                <img class="img-fluid coupon_modal_img me-4" src="{{ coupon.image.url }}" alt="">
                                            {% endif %}
                                            <div class="d-flex flex-column h-100">
                                                <div>Coupon Code: "{{ coupon.coupon_code }}"</div>
                                                <small>₹{{ coupon.discount_price }} off at min shopping of ₹{{coupon.minimum_price}}</small>
                                                <p class="text-success">SAVE ₹{{ coupon.discount_price }} ON THIS ORDER</p>
                                                <a href="" class="text-decoration-none" style="color: #F6921E;">View T&C</a>
                                            </div>
                                        </div>
                                        <form action="{% url 'cart:cart' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="coupon" value="{{ coupon.coupon_code }}">
                                            <button type="submit" class="text-decoration-none btn" style="color: #F6921E;">Apply</button>
                                        </form>
                                    </div>
                                    {% if not forloop.last %}
                                        <div class="my-4" style="border: 1px solid #e3e3e3;"></div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if cart.coupon %}
                    <div class="mt-4 d-flex justify-content-between align-items-center p-4" id="coupon_name" style="border: 1px solid #f6911e75; border-radius: 10px;">
                        <div class="d-flex">
                            <div class="d-flex justify-content-center align-items-center text-white coupon_img">
                                <span>%</span>
                            </div>
                            <div class="d-flex justify-content-center align-items-center ms-4">
                                <span class="fw-bold me-2">{{ cart.coupon.coupon_code }}</span> applied
                            </div>
                        </div>
                        <a href="{% url 'discount:remove_coupon' cart.id %}" class="text-danger text-decoration-none">Remove</a>
                    </div>
                    <div class="mt-4 d-flex align-items-center p-4" id="coupon_savings" style="background-color: #f6911e44; border-radius: 10px;">
                        <img class="img-fluid" style="width: 50px;" src="{% static 'img/coins.png' %}" alt="">
                        <div class="d-flex">
                            <div class="d-flex justify-content-center align-items-center ms-4">
                                You're saving total ₹{{ cart.coupon.discount_price }} on this order!
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    {% if cart_items %}
                    <h5 class="mt-5" id="grand_total_heading">Grand Total: Rs <span id="grand_total">{{ cart_total }}</span></h5>
                    {% endif %}

                </div>
            </div>
            {% endif %}
        </div>
    </div>




    {% if cart.cartitems %}
        {% include 'includes/footer.html' %}
    {% endif %}

{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>


  <button id="toastBtn" class="btn btn-primary">Show Toast</button>

  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div class="toast" id="myToast">
      <div class="toast-header text-bg-danger">
        <div class="me-auto">Bootstrap</div>
        <small>11 mins ago</small>
      </div>
      <div class="toast-body text-bg-danger">
        Hello World! This is a toast message!
      </div>
    </div>
  </div>



  <script src="../assets/js/bootstrap.bundle.min.js"></script>

  <script>
    const toastTrigger = document.querySelector('#toastBtn');
    const toast = document.querySelector('#myToast');

    if (toastTrigger) {
      const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toast);

      toastTrigger.addEventListener('click', () => {
        toastBootstrap.show();
      });
    }
  </script>

</body>
</html>